Migrate FrontDesk endpoints to FastEndpoints - Part 1
It introduces an EmptyBaseRequest. Otherwise, GET requests without
parameters break with:

System.NotSupportedException: Only request DTOs with publicly accessible
properties are supported for request binding. Offending type:
[BlazorShared.Models.AppointmentType.ListAppointmentTypeRequest]
   at FastEndpoints.RequestBinder`1..cctor()

The EmptyBaseRequest has a dummy nullable property to make FastEndpoints
binding work.